version: "3.9"
services:
  jelly-model:
    image: jelly-model:xception-v4-001
  gateway:
    image: jelly-model-gateway:001
    environment:
      - TF_SERVING_HOST=jelly-model:8500
    ports:
      - "9696:9696"
